### ISSUE TITLE
After unloading temperature stays at 250C and cannot start new print

### ISSUE THREAD

**Issue by php4umagento** [xperiments-in/xtouch#63] opened 2023-12-07 11:49 UTC
**Describe the bug**
After unloading temperature stays at 250C and cannot start new print

**To Reproduce**
1. Go to Filaments tab
2. Click on 'UNLOAD'
3. Wait for printer to heat up, cut filament then pull filament out of the tube
4. Observe that temperature stays on 250C

**Expected behavior**
Printer should start cooling down and accept new prints

**XTOUCH (please complete the following information):**
 - 0.9.24

**Printers (please complete the following information):**
 - Device: P1P, P1S
 - FW Version - 01.04.02.00

**Comment by xperiments** [comment] 2023-12-13 04:31
duplicate of #47

**Closed by xperiments** 2023-12-13 04:31 UTC
