### ISSUE TITLE
Large delay in nozzle cooling after pressing "Done" during load filament

### ISSUE THREAD

**Issue by brandonkish** [xperiments-in/xtouch#50] opened 2023-11-06 19:20 UTC
**Describe the bug**

1. Pressing "Done" button during the "Load" filament process does not reset the nozzle temperature to the cooling temperature until a very long time.

**To Reproduce**
1. Power cycle Bambu Printer
2. Power cycle xTouch display
3. Go to "Filament screen" on xTouch.
4. Press "Yes" to confirm load process on xTouch.
![20231106_130141](https://github.com/xperiments-in/xtouch/assets/7042606/46a471ad-16a8-493b-9e61-d0e4f8dda666)

5. Wait for nozzle to heat on Bambu Printer, and for Done / Confirm prompt to display on xTouch
![20231106_130119](https://github.com/xperiments-in/xtouch/assets/7042606/bc49794e-c449-4d91-a1af-f45934147435)

6. Press the "Done" button on xTouch display.
7. Wait several minutes to confirm on the xTouch display and Bambu Printer that the nozzle temp is still at 250*C
8. Confirm nozzle temp is only set to cool temperature several minutes after load process completed.

**Expected behavior**

1. After pressing "Done" during the "Load" filament process, the nozzle temp should be set to a cool temp (~42*C) a few seconds after nozzle completes clean process.

**Screenshots**
![20231106_130141](https://github.com/xperiments-in/xtouch/assets/7042606/b5e33f1e-2df5-4532-84d0-5fdb7603857c)

**XTOUCH (please complete the following information):**
 - FW: v0.9.24

**Printers (please complete the following information):**
 - Device: P1S
 - FW Version: 01.04.02.00
-  AMS units: 0

**Additional context**

**NOTE** I believe some of the functionality for the "Confirm" and "Done" buttons are reversed. The "Confirm" button seems to cool the nozzle but, it shouldn't since it prompts again afterwards to confirm again. And the "Done" button is cooling the nozzle. I believe these are simply backwards.

**Comment by kenkamm** [comment] 2023-11-22 17:04
When loading, I press "Done" on mine and the filament will feed a bit as expected, but then the temp goes up to 260 and stays there.

**Comment by xperiments** [comment] 2023-12-13 04:31
duplicate of #47

**Closed by xperiments** 2023-12-13 04:31 UTC
