### ISSUE TITLE
Please bring back LAN support!

### ISSUE THREAD

**Issue by cwkean87** [xperiments-in/xtouch#133] opened 2024-06-21 07:02 UTC
LAN support no longer works after the latest OTA. that's sad as i only use LAN printing and never wanna use the cloud services. pls help！thank you very much!

**Comment by xperiments** [comment] 2024-06-21 11:02
duplicate of #120

**Closed by xperiments** 2024-06-21 11:02 UTC
Labels: duplicate

**Comment by cwkean87** [comment] 2024-06-21 12:22
awesome. thank you!
