### ISSUE TITLE
Popups appear everytime I Load/Unload and Extrude filament

### ISSUE THREAD

**Issue by michaltulach** [xperiments-in/xtouch#19] opened 2023-10-15 18:16 UTC
## Feature Description

When I Load, Unload or Extrude filement using Xtouch there appear popups which says what I should do next. When you get used to your printer and Xtouch these popups are a bit annoying beacuse you have to click everytime. When Loading or Unloading it´s moreless OK but when you want to extrude more filement using Xtouch you have to confirm that the nozzle temperature is more than 170 ℃ and then the printer extrudes and screen switches back to home screen and you have to go back to filament management and repeat this proces to extrude the desired amount of filament.

## Justification

It could save my time and more clicking.

## Suggested Implementation (if you have one)

There could be a switch in setting where you could select if you want to show these popups.

## Screenshots or Examples (if applicable)

There is a step by step what I do when I want to extrude filament.

![20231015_194317](https://github.com/xperiments-in/xtouch/assets/147524087/89e01904-47e8-465a-a3b7-1748f7550d6c)

![20231015_194248](https://github.com/xperiments-in/xtouch/assets/147524087/6849ec98-b716-4200-829b-662274237b2f)

![20231015_194252](https://github.com/xperiments-in/xtouch/assets/147524087/12c3ca69-5b39-49e0-903e-3b79c6b6e78f)

![20231015_194259](https://github.com/xperiments-in/xtouch/assets/147524087/a9e59a69-2c86-4f3a-82c0-f251b52a49ae)

![20231015_194304](https://github.com/xperiments-in/xtouch/assets/147524087/3ab80953-f781-4802-9bb4-7c5b93d86764)

![20231015_194241](https://github.com/xperiments-in/xtouch/assets/147524087/e83ee079-6f0d-465c-813f-9471e14913e8)

**Comment by xperiments** [comment] 2023-10-17 22:24
Duplicate of #14. Please refer to this issue. Thanks

**Closed by xperiments** 2023-10-17 22:24 UTC
